[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "mcp-payments"
version = "0.1.0"
description = "MCP payments server"
requires-python = ">=3.11"

