global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # MCP Payments Server metrics
  - job_name: 'mcp-payments'
    static_configs:
      - targets: ['mcp-payments:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PostgreSQL metrics (if using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187']
    scrape_interval: 10s

  # Redis metrics (if using redis_exporter)  
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']
    scrape_interval: 10s

  # RabbitMQ metrics
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    scrape_interval: 10s

  # Node/system metrics (if using node_exporter)
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 10s 